dist: xenial
language: go
go:
  - "1.13"

notifications:
  email:
    recipients:
      - knqyf263@gmail.com
    on_success: change
    on_failure: always

stages:
  - 'NVD'
  - 'Alpine Issue Tracker'
  - 'Debian Security Bug Tracker'
  - 'Debian OVAL'
  - 'Ubuntu CVE Tracker'
  - 'Amazon Linux AMI Security Advisory'
  - 'Oracle Linux OVAL'
  - 'Red Hat OVAL'
  - 'Photon CVE Advisory'
  - 'SUSE CVRF'
  - 'Red Hat Security Data API 2019-2020'
  - 'Red Hat Security Data API 2018'
  - 'Red Hat Security Data API 2017'
  - 'Red Hat Security Data API 2016'
  - 'Red Hat Security Data API 2015'
  - 'Red Hat Security Data API 2014'
  - 'Red Hat Security Data API 2013'
  - 'Red Hat Security Data API 2012'
  - 'Red Hat Security Data API 2009-2011'
  - 'Red Hat Security Data API 2003-2008'
  - 'Red Hat Security Data API 1996-2002'

jobs:
  include:
    - stage: 'NVD'
      if: type = cron
      script:
        - go run main.go -target nvd

    - stage: 'Alpine Issue Tracker'
      if: type = cron
      script:
        - go run main.go -target alpine

    - stage: 'Debian Security Bug Tracker'
      if: type = cron
      script:
        - go run main.go -target debian

    - stage: 'Debian OVAL'
      if: type = cron
      script:
        - go run main.go -target debian-oval

    - stage: 'Ubuntu CVE Tracker'
      if: type = cron
      script:
        - go run main.go -target ubuntu

    - stage: 'Amazon Linux AMI Security Advisory'
      if: type = cron
      script:
        - go run main.go -target amazon

    - stage: 'Oracle Linux OVAL'
      if: type = cron
      script:
        - go run main.go -target oracle-oval

    - stage: 'Red Hat OVAL'
      if: type = cron
      script:
        - go run main.go -target redhat-oval

    - stage: 'Photon CVE Advisory'
      if: type = cron
      script:
        - go run main.go -target photon

    - stage: 'GitHub Security Advisory'
      if: type = cron
      script:
        - go run main.go -target ghsa

    - stage: 'SUSE CVRF'
      if: type = cron
      script:
        - go run main.go -target suse-cvrf

    # split RedHat job due to timeout
    - stage: 'Red Hat Security Data API 1996-2002'
      if: type = cron
      script:
        - go run main.go -target redhat -years 1996,1997,1998,1999,2000,2001,2002
    - stage: 'Red Hat Security Data API 2003-2008'
      if: type = cron
      script:
        - go run main.go -target redhat -years 2003,2004,2005,2006,2007,2008
    - stage: 'Red Hat Security Data API 2009-2011'
      if: type = cron
      script:
        - go run main.go -target redhat -years 2009,2010,2011
    - stage: 'Red Hat Security Data API 2012'
      if: type = cron
      script:
        - go run main.go -target redhat -years 2012
    - stage: 'Red Hat Security Data API 2013'
      if: type = cron
      script:
        - go run main.go -target redhat -years 2013
    - stage: 'Red Hat Security Data API 2014'
      if: type = cron
      script:
        - go run main.go -target redhat -years 2014
    - stage: 'Red Hat Security Data API 2015'
      if: type = cron
      script:
        - go run main.go -target redhat -years 2015
    - stage: 'Red Hat Security Data API 2016'
      if: type = cron
      script:
        - go run main.go -target redhat -years 2016
    - stage: 'Red Hat Security Data API 2017'
      if: type = cron
      script:
        - go run main.go -target redhat -years 2017
    - stage: 'Red Hat Security Data API 2018'
      if: type = cron
      script:
        - go run main.go -target redhat -years 2018
    - stage: 'Red Hat Security Data API 2019-2020'
      if: type = cron
      script:
        - go run main.go -target redhat -years 2019,2020
