name: Update vuln-list-redhat repo
on:
  schedule:
  - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  update:
    name: Update vuln-list-redhat
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.ORG_REPO_TOKEN }}
      VULN_LIST_DIR: "vuln-list-redhat"
    steps:
    - name: Check out code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: Set up Go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      with:
        go-version-file: go.mod

    - name: Check out vuln-list-redhat repo
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        repository: ${{ github.repository_owner }}/${{ env.VULN_LIST_DIR }}
        token: ${{ secrets.ORG_REPO_TOKEN }}
        path: ${{ env.VULN_LIST_DIR }}

    - name: Setup github user email and name
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"

    - name: Compile vuln-list-update
      run: go build -o vuln-list-update .

    - if: always()
      name: Red Hat OVALv2
      run: ./scripts/update.sh redhat-oval "Red Hat OVAL v2"

    - if: always()
      name: Red Hat Security Data API
      run: ./scripts/update.sh redhat "Red Hat Security Data API"

    - if: always()
      name: Red Hat CSAF VEX
      run: ./scripts/update.sh redhat-csaf-vex "Red Hat CSAF VEX"

    - name: Microsoft Teams Notification
      uses: Skitionek/notify-microsoft-teams@e7a2493ac87dad8aa7a62f079f295e54ff511d88
      if: failure()
      with:
        webhook_url: ${{ secrets.TRIVY_MSTEAMS_WEBHOOK }}
        needs: ${{ toJson(needs) }}
        job: ${{ toJson(job) }}
        steps: ${{ toJson(steps) }}