name: Update vuln-list-redhat repo
on:
  workflow_dispatch:

jobs:
  update:
    name: Update vuln-list-redhat
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      VULN_LIST_DIR: "vuln-list-redhat"
    steps:
    # vuln-list-redhat dir uses more than 20GB of storage
    - name: Free disk space
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/local/.ghcup
        sudo rm -rf /usr/local/share/boost
        sudo rm -rf /opt/hostedtoolcache/CodeQL
        sudo docker image prune --all --force > /dev/null
        df -h

    - name: Check out code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        persist-credentials: false

    - name: Set up Go
      uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
      with:
        go-version-file: go.mod

    - name: Check out vuln-list-redhat repo
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        repository: ${{ github.repository_owner }}/${{ env.VULN_LIST_DIR }}
        path: ${{ env.VULN_LIST_DIR }}
        persist-credentials: false

    - name: Compile vuln-list-update
      run: go build -o vuln-list-update .

    - name: Red Hat CSAF VEX
      run: ./vuln-list-update -vuln-list-dir "$VULN_LIST_DIR" -target redhat-csaf-vex

    - name: Commit and push
      env:
        GH_TOKEN: ${{ secrets.VULN_LIST_TOKEN }}
        OWNER: ${{ github.repository_owner }}
      run: |
        cd "$VULN_LIST_DIR"
        git config user.email "action@github.com"
        git config user.name "GitHub Action"
        git remote set-url origin "https://x-access-token:${GH_TOKEN}@github.com/${OWNER}/${VULN_LIST_DIR}.git"
        git switch -c "resync-${{ github.run_id }}"
        git add .
        git commit -m "Red Hat CSAF VEX"
        git push -u origin HEAD

    - name: Report
      if: always()
      run: |
        df -h
        du -sh "$VULN_LIST_DIR/csaf-vex"
        find "$VULN_LIST_DIR/csaf-vex" -type f | wc -l
        git -C "$VULN_LIST_DIR" status --porcelain | cut -c1-2 | sort | uniq -c
